feat: add anchors link button on section title hover
BlockchainEtSociete/blockchainsociete.org pull request #84
Opened 2022-01-04 17:30 UTC by ftreguer

2022-01-04 17:36 UTC, dlecan commented
:star_struck:

2022-01-04 17:38 UTC, dlecan commented
Ok pour le fonctionnel, ça répond à ma demande

@Nigui pour le fond technique

2022-01-05 15:59 UTC, Nigui requested changes
top ! 
1 commentaire
+ on pourrait virer margin du "partial" et plutôt le mettre à chaque fois dans le layout appelant ?

2022-01-05 15:59 UTC, Nigui commented on themes/custom-blist/assets/css/site.css
> +.section-title:hover .section-link-icon, .section-link-icon:hover {
Utilise directement les outils de tailwind, c'est fait pour 
https://v2.tailwindcss.com/docs/hover-focus-and-other-states

2022-01-07 12:51 UTC, ftreguer commented
@Nigui modif faites

2022-01-07 15:24 UTC, Nigui requested changes
2 petits commentaires à voir dans le code

2022-01-07 15:24 UTC, Nigui commented on themes/custom-blist/assets/css/site.css
> +.section-title:hover .section-link-icon, .section-link-icon:hover {
+1

2022-01-07 15:24 UTC, Nigui commented on themes/custom-blist/layouts/partials/homepage/social.html
> +      "fontSize" "text-2xl" ) }}
attention, après rebase la fontSize a changée pour cette section (homogénéisée avec les autres sections). On peut donc le supprimer des paramètres du composant

2022-01-11 08:35 UTC, ftreguer commented
@Nigui tailwind ok + homogénéisation du titre pour la section socials

2022-01-11 09:18 UTC, merged